### ISSUE TITLE
Bot refused to join vc on web

### ISSUE THREAD

**Issue by hokagay7** [typekcz/beepboop-steam#29]
I was using web dockerfile; the bot managed to go online but refused to join voice chat.

This is my logs file:
[steamvc-5c98f4869d-zkr5c_20240401T172633.655-20240401T172759.479.log](https://github.com/typekcz/beepboop-steam/files/14822144/steamvc-5c98f4869d-zkr5c_20240401T172633.655-20240401T172759.479.log)

It was hosted on northflank (free plan).

**edit:** i tried using client dockerfile. steam keep exiting
this is the logs file:
[steamvc-7f964b7cc4-rwn8k_20240401T175533.740-20240401T175545.755.log](https://github.com/typekcz/beepboop-steam/files/14822256/steamvc-7f964b7cc4-rwn8k_20240401T175533.740-20240401T175545.755.log)

**Comment by typekcz** [comment]
Check `/screen` on the bot's web server, that could tell what's up in the UI.

Maybe Northflank is a little slower and 10s is not enough for it to load the Steam chat. Can you try it with modified timeout at:
https://github.com/typekcz/beepboop-steam/blob/a35a4290a59064b3c12b0212e58eb7bea5db699e/src/steam-api/steam-browser-api.js#L98

Client mode is more resource heavy, so that may be the reason that Steam is crashing. I haven't tested client mode in a long time so maybe it's just broken.

**Comment by hokagay7** [comment]
Modifying the timeout did the trick, but now the bot doesn't play anything. It did join the channel, but no output.

![2024-04-01 21_12_42-Friends List - Mutakhalifan](https://github.com/typekcz/beepboop-steam/assets/68209911/60120816-e2cf-472b-a592-61fbf381dd5d)

This is one of the logs:
> 2024-04-01T13:16:40.963568998Z stdout F handleMessage Mutakhalifan | Home : [mention=1190757344]@Beep Beep[/mention] instant thomas
2024-04-01T13:16:42.663710811Z stdout F Page error: TypeError: Failed to execute 'getStats' on 'RTCPeerConnection': parameter 1 is not of type 'MediaStreamTrack'.
2024-04-01T13:16:42.66376063Z stdout F     at j.ProcessReceiverStatsReport (https://community.akamai.steamstatic.com/public/javascript/webui/friends.js?v=8UWTKMNnLosQ&l=english:14:675397)
2024-04-01T13:16:42.663764655Z stdout F     at Ie (https://community.akamai.steamstatic.com/public/javascript/webui/libraries.js?v=JzjEkBeF4yXi&l=english:22:37516)
2024-04-01T13:16:42.663766933Z stdout F     at ProcessReceiverStatsReport (https://community.akamai.steamstatic.com/public/javascript/webui/libraries.js?v=JzjEkBeF4yXi&l=english:22:37016)

**Comment by typekcz** [comment]
Some things are broken, youtube search works only from web interface. Instant doesn't work, because of their DDoS protection.

I don't know what's up with these RTC messages, sometimes they appear, sometimes not, sometimes it can be ignored.

Can you try running version from [develop branch](https://github.com/typekcz/beepboop-steam/tree/develop), I'm currently trying to fix some issues there, but mostly kept struggling with Chromium, codecs and Puppeteer.

**Comment by hokagay7** [comment]
same issue persist. Its okay no rush, i can wait :)

**Comment by typekcz** [comment]
Did you rebuild the image with `--build` parameter?
